apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenthub-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: documenthub
  template:
    metadata:
      labels:
        app: documenthub
    spec:
      containers:
        - name: documenthub
          image: document-hub:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb-service:27017/documenthub
---
apiVersion: v1
kind: Service
metadata:
  name: documenthub-service
spec:
  selector:
    app: documenthub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer